#!/bin/bash

rm -f result

corr=0;

for i in `seq 1 5`; do
    rm -f tempresult
    ./RadixSort.exe < ./testfiles/t$i >> tempresult
    diff tempresult ./testfiles/o$i >> tempcnt
    if [ -s tempcnt ] ; then
      echo "Incorrect for $i th example."
    else
      echo "  Correct for $i th example.";
      ((corr=corr+1))
    fi;

    #echo "==================" >> result
    echo $(whoami) "test" $i: ${corr}/5 >> result
    #cat tempresult1 >> result

done

echo $corr/5;

rm -f tempresult
rm -f tempcnt

